### ISSUE TITLE
Can't compile: ‘index_factory’ is not a member of ‘faiss’

### ISSUE THREAD

**Issue by KimalIsaev** [ZJULearning/efanna_graph#3]
Hello, i'm trying to compile with faiss.
But after command "make" there is error:
```
/home/kimal/Kema/gitty/efanna_graph/src/index_pq.cpp: In member function ‘virtual void efanna2e::IndexPQ::Build(size_t, const float*, const efanna2e::Parameters&)’:
/home/kimal/Kema/gitty/efanna_graph/src/index_pq.cpp:46:18: error: ‘index_factory’ is not a member of ‘faiss’
   46 |   index = faiss::index_factory(dimension_, pq_index_key.c_str());
      |   
```
![Screenshot from 2019-12-21 20-42-40](https://user-images.githubusercontent.com/27774041/71311697-85348d80-2432-11ea-99c6-15cf4864ab0d.png)
I'm using Fedora.
I've already compiled faiss in "extern_libraries" directory.
Is there something I've missed?

Thank you for reading. I'll be glad to see any response.

**Comment by melong007** [comment]
I just got the same error with you;  Fix method as follow:
a. cd  extern_libraries && mkdir build && cd build && git clone ...faiss..;
b.  compile the  faiss:  ./configure  --without-cuda --prefix=../faiss_lib{need change to abs path}; make && make install;  
c.  faiss install to faiss_lib dir;
d. cd faiss_lib && mv lib  lib/faiss/; 
e. At last,  the layout,  you can take a look to CMakeLists.txt;
└── faiss
    ├── impl
    ├── lib
    └── utils
f.  add  #include <faiss/index_factory.h> to  src/index_pq.cpp

**Comment by macanv** [comment]
as @melong007  sloution, just add #include <faiss/index_factory.h> to src/index_pq.cpp done!

**Comment by KimalIsaev** [comment]
Thanks.
